application: vg-gtug-news
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /json
  static_dir: json
  mime_type: application/json 
- url: /images
  static_dir: images
- url: /.*
  script: todo.py